POST http://localhost:3000/api/create-user
Content-Type: application/json

{
    "currency": "ETH",
    "balance": "100",
    "token": "1234567898765432-ETE",
    "id": 123456
}
###

POST http://localhost:3000/api/delete-user
Content-Type: application/json

{
    "token": "1234567898765432-ETH"
}
###

POST http://localhost:3000/api/cashin-user
Content-Type: application/json

{
    "token": "1234567898765432-ETE",
    "amount": 150,
    "id": 123459
}
###

POST http://localhost:3000/api/cashout-user
Content-Type: application/json

{
    "token": "1234567898765432-ETH",
    "amount": 1500,
    "id": 123457
}
###
