POST http://localhost:3000/billing
Content-Type: application/json

{
    "name": "login",
    "id": "123456789",
    "timestamp": "2019-10-22 24:00:12",
    "session": "aserdfsh65764",
    "token": "123456789"
}

###

POST http://localhost:3000/billing
Content-Type: application/json

{
    "name": "transaction",
    "id": "123456789",
    "timestamp": "2019-10-22 24:00:12",
    "session": "aserdfsh65764",
    "plus": 10,
    "minus": 0,
    "token": "123456789"
}

###

POST http://localhost:3000/billing
Content-Type: application/json

{
  "name": "sync",
  "id": "123456789",
  "timestamp": "2019-10-22 24:00:12",
  "session": "aserdfsh65764",
  "token": "123456789"
}

###