POST http://localhost:3000/billing
Content-Type: application/json

{
    "name": "login",
    "id": "123456779",
    "timestamp": "2019-10-22 24:00:12",
    "session": "aserdfsh65764",
    "token": "1234567898765432-ETE"
}

###

POST http://localhost:3000/billing
Content-Type: application/json

{
    "name": "transaction",
    "id": "123456789",
    "timestamp": "2019-10-22 24:00:12",
    "session": "aserdfsh65764",
    "plus": 0,
    "minus": 20,
    "token": "1234567898765432-ET"
}

###

POST http://localhost:3000/billing
Content-Type: application/json

{
  "name": "sync",
  "id": "123456789",
  "timestamp": "2019-10-22 24:00:12",
  "session": "aserdfsh65764",
  "token": "1234567898765432-ET"
}

###

POST http://localhost:3000/billing
Content-Type: application/json

{
  "name": "logout",
  "id": "123456789",
  "timestamp": "2019-10-22 24:00:12",
  "session": "aserdfsh65764",
  "token": "1234567898765432-ETE"
}

###